### ISSUE TITLE
simulation.py fails after creating 199 Images

### ISSUE THREAD

**Issue by georgeha** [CFN-softbio/cms_generators#1]
Hello,

I am running the simulation.py software. 
After creating 199 Images the software is trying to create Image 0 again, and it fails.
Here is the Traceback message:
```
 Image 199 (000000c7)
saving hdf5 file to /home/georgeha/data/e9fb4e95/000000c7.hd5
Experiment 100 (e9fb4e95)
  Image 0 (00000000)
saving hdf5 file to /home/georgeha/data/e9fb4e95/00000000.hd5
Traceback (most recent call last):
  File "simulation.py", line 1237, in <module>
    save_data(det_image.astype(np.uint32), run_dir, image_idx_str, tags)
  File "simulation.py", line 1163, in save_data
    f.create_dataset(name='img', shape = det_image.shape, data=det_image)
  File "/home/georgeha/anaconda2/envs/lightflow/lib/python3.6/site-packages/h5py/_hl/group.py", line 109, in create_dataset
    self[name] = dset
  File "/home/georgeha/anaconda2/envs/lightflow/lib/python3.6/site-packages/h5py/_hl/group.py", line 277, in __setitem__
    h5o.link(obj.id, self.id, name, lcpl=lcpl, lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 202, in h5py.h5o.link
RuntimeError: Unable to create link (name already exists)
```

**Comment by kevinyager** [comment]
On line 1209 it's defining how many images to generate ("for image_idx in range(200):"). Just update that to some other range (e.g. "for image_idx in range(200, 8001):").

**Comment by georgeha** [comment]
Thank you Kevin!
It works fine.
